### PR TITLE
Fix error message showing even when debugging is set to false

### LINKED ISSUE #23: Extraneous debug appearing even when there is a live video scheduled
Debugging from` EmbedYoutubeLiveStreaming::__set_state(` appearing even when there is a live video scheduled (I've got used to the error if there's nothing scheduled and I have "Show scheduled live videos" as a fallback :D) I'm guessing this is new in 1.8.4.

See https://werringtonparish.org.uk/services/

### PR DESCRIPTION
**Pull request by hosungs**
First of all, thanks a lot for the great plugin! I tried this on a Wordpress site I help with, and it works great when the live streaming is in session, but I noticed that the plugin shows the red error message when the live streaming is not in session, even if the debugging setting is set to false. I looked around and It appears that this was addressed at https://wordpress.org/support/topic/needs-an-update-27/#post-16487899 and likely fixed, but it looks to me the issue is still present, thus proposing this fix.

Being a php novice, I'm not sure if this is the right/desirable fix, but apparently the existing `get_option('youtube_live_settings', 'debugging')`  seems always true (according to the Wordpress `get_option()` doc https://developer.wordpress.org/reference/functions/get_option/ and the PHP semantics about the truthiness of a non-empty string), and displays the error message always even when the debugging is set to false in the plugin settings. Please do comment with a better fix, and I'll add another commit to reflect your feedback. Thanks again!

Fixes #23.

### CODE REVIEW

File: wp-youtube-live.php [hunk 1]
```diff
@@ -188,7 +188,7 @@ function get_youtube_live_content( $request_options ) {
 	}
 
 	// debugging.
-	if ( get_option( 'youtube_live_settings', 'debugging' ) && is_user_logged_in() ) {
+	if ( 'false' !== $youtube_options['debugging'] && is_user_logged_in() ) {
```
Comment (macbookandrew) [inline wp-youtube-live.php:191]: How about this rather than checking for the string `'false'`?

```suggestion
	if ( $youtube_options['debugging'] && is_user_logged_in() ) {
```

**Review by macbookandrew — CHANGES_REQUESTED** [review]
Thanks for the PR. You’re right…I’m not sure what I was thinking when I wrote that 😆

File: wp-youtube-live.php (hunk 1 above)
Comment (hosungs) [reply wp-youtube-live.php:191]: Thanks much for your quick review! Re: your suggestion, in fact, that's exactly what I did at the beginning, and it didn't work, so it kept me scratching my head. I eventually delved into the `wp_options` table (whatever the table name is), and saw the content of the options. Not sure the exact format (didn't look like json-encoding), but I figured the setting value is not a boolean but a string. And a non-empty string `'false'` is actually a boolean true, and it made sense. I also tried `boolval()` after looking up the web for string->boolean conversion, but of course that applies to an empty string as false, not the literal `'false'` to false. That's what made me to try this string comparison (I know it's ugly and I don't like it), and it worked. I suspect a proper fix would be to set the correct type for the setting, but that's beyond me, and I wouldn't want to blow up this PR that much, so this quick/small fix.

Just FYI, https://www.insightmeditationcenter.org/2024/01/hs-test-youtube-live-plugin/ is where I installed your plugin, applies this fix, and used the short code in the post. Without this fix, it kept showing the red error message even with the plugin's debugging setting set to false. Thanks again for the great plugin!

Comment (macbookandrew) [reply wp-youtube-live.php:191]: > Not sure the exact format (didn't look like json-encoding)

No, WP uses PHP’s [`serialize()` function](https://www.php.net/manual/en/function.serialize.php) for options, meta etc.

Ah, it’s storing true/false as strings because they’re strings [here](https://github.com/macbookandrew/wp-youtube-live/blob/9a35b2986e2f0b79fc340857e175a66075f59b7d/inc/admin.php#L307).

How about we check for the positive condition rather than absence of negative condition?

```suggestion
	if ( 'true' === $youtube_options['debugging'] && is_user_logged_in() ) {
```

**Comment by macbookandrew** [comment]
Note: this should fix #23

**Review by macbookandrew — APPROVED** [review]
Thanks for the fix!
